/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.habitatSystem.view;

import ec.edu.espe.habitatSystem.controller.IguanaController;
import ec.edu.espe.habitatSystem.model.Iguana;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA TONATO
 */
public class FrmIguana extends javax.swing.JFrame {

    /**
     * Creates new form FrmIguanas
     */
    public FrmIguana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSpeciesName = new javax.swing.JTextField();
        btnShowData = new javax.swing.JButton();
        cmbSkinColor = new javax.swing.JComboBox<>();
        txtAge = new javax.swing.JTextField();
        cmbMoves = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        cmbSpecies = new javax.swing.JComboBox<>();
        txtLocation = new javax.swing.JTextField();
        txtWeight = new javax.swing.JTextField();
        txtFeeding = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDeleteall = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        btnLeave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtSpeciesName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSpeciesName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSpeciesName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpeciesNameActionPerformed(evt);
            }
        });

        btnShowData.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnShowData.setText("SHOW DATA");
        btnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDataActionPerformed(evt);
            }
        });

        cmbSkinColor.setFont(new java.awt.Font("Century Schoolbook", 1, 11)); // NOI18N
        cmbSkinColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light Green", "Lime Green", "Yellow", "Reddish Orange", "Gray", "Blue", "Coffe", "Spring Green" }));

        txtAge.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAge.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        cmbMoves.setFont(new java.awt.Font("Century Schoolbook", 1, 11)); // NOI18N
        cmbMoves.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "The iguana is an excellent Climber, Swimmer, Fast", "Slow movements of Old age and little Swimming", "Not being able to Swim in deserts and be an excellent climber" }));

        btnSave.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbSpecies.setFont(new java.awt.Font("Century Schoolbook", 1, 11)); // NOI18N
        cmbSpecies.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Green Iguana", "Desert Iguana", "Marine Iguana" }));

        txtLocation.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtLocation.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtWeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtWeight.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtFeeding.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtFeeding.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("212 Leahlee Sans", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("IGUANA");

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel2.setText("Species Name:");

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel3.setText("Species:");

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel4.setText("Skin Color:");

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel6.setText("Age:");

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel7.setText("Feeding:");

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel8.setText("Weight:");

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel9.setText("Location:");

        btnDeleteall.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeleteall.setText("DELETE ALL");
        btnDeleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteallActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel10.setText("Moves:");

        btnLeave.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnLeave.setText(" LEAVE");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        jTextData.setColumns(20);
        jTextData.setRows(5);
        jScrollPane2.setViewportView(jTextData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(236, 236, 236)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnSave)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel8)
                                        .addComponent(jLabel7)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtLocation, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtWeight, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtFeeding, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbSkinColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(cmbSpecies, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtSpeciesName, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cmbMoves, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(58, 58, 58)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(btnDeleteall)
                                            .addComponent(btnShowData))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLeave))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(128, 128, 128)
                                .addComponent(jLabel1))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSpeciesName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbSpecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbSkinColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtAge))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtFeeding, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbMoves, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnShowData)
                    .addComponent(btnLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSpeciesNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpeciesNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpeciesNameActionPerformed

    private void btnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDataActionPerformed
       IguanaController IguanaController = new IguanaController();
       jTextData.setText(IguanaController.read()); 
                
    }//GEN-LAST:event_btnShowDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Iguana Iguana;
        String SpeciesName;
        String Species;
        String SkinColor;
        int Age;
        String Feeding;
        int Weight;
        String Location;
        String Moves;

        IguanaController IguanaController = new IguanaController();

        SpeciesName = txtSpeciesName.getText();
        Species = cmbSpecies.getSelectedItem().toString();
        SkinColor = cmbSkinColor.getSelectedItem().toString();
        Age =  Integer.parseInt(txtAge.getText());
        Feeding = txtFeeding.getText();
        Weight = Integer.parseInt(txtWeight.getText());
        Location = txtLocation.getText();
        Moves = cmbMoves.getSelectedItem().toString();

        Iguana =new Iguana (SpeciesName,Species,SkinColor,Age,Feeding, Weight,Location,Moves);

        IguanaController.save(Iguana);

        JOptionPane.showMessageDialog(rootPane,Iguana.getSpeciesname());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteallActionPerformed
        int integer = 0;

        txtSpeciesName.setText("");
        txtAge.setText("");
        txtFeeding.setText("");
        txtWeight.setText("");
        txtLocation.setText("");

    }//GEN-LAST:event_btnDeleteallActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmIguana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmIguana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmIguana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmIguana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmIguana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteall;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowData;
    private javax.swing.JComboBox<String> cmbMoves;
    private javax.swing.JComboBox<String> cmbSkinColor;
    private javax.swing.JComboBox<String> cmbSpecies;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextData;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFeeding;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JTextField txtSpeciesName;
    private javax.swing.JTextField txtWeight;
    // End of variables declaration//GEN-END:variables

}
