/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.espe.book.view;

import ec.edu.espe.book.controller.BookController;
import ec.edu.espe.book.model.Book;
import javax.swing.JOptionPane;

/**
 *
 * @author FAMILIA TONATO
 */
public class FrmBook extends javax.swing.JFrame {

    /**
     * Creates new form FrmIguanas
     */
    public FrmBook() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNameBook = new javax.swing.JTextField();
        btnShowData = new javax.swing.JButton();
        cmbBookColor = new javax.swing.JComboBox<>();
        txtAuthorBook = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        cmbBookSize = new javax.swing.JComboBox<>();
        txtBookEditor = new javax.swing.JTextField();
        txtYearPublished = new javax.swing.JTextField();
        txtEdittionBook = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btnDeleteall = new javax.swing.JButton();
        btnLeave = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextData = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtNameBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNameBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtNameBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameBookActionPerformed(evt);
            }
        });

        btnShowData.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnShowData.setText("SHOW DATA");
        btnShowData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowDataActionPerformed(evt);
            }
        });

        cmbBookColor.setFont(new java.awt.Font("Century Schoolbook", 1, 11)); // NOI18N
        cmbBookColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Light Green", "Lime Green", "Yellow", "Reddish Orange", "Gray", "Blue", "Coffe", "Spring Green", "Red", "Black" }));

        txtAuthorBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtAuthorBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnSave.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmbBookSize.setFont(new java.awt.Font("Century Schoolbook", 1, 11)); // NOI18N
        cmbBookSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small book", "Medium book", "Big Book" }));

        txtBookEditor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtBookEditor.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtYearPublished.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtYearPublished.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtEdittionBook.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEdittionBook.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel1.setFont(new java.awt.Font("212 Leahlee Sans", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setText("BOOK");

        jLabel2.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel2.setText("name of the book");

        jLabel3.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel3.setText(" book color");

        jLabel4.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel4.setText(" book size");

        jLabel6.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel6.setText(" author of the book");

        jLabel7.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel7.setText("Edition of the book");

        jLabel8.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel8.setText("year published");

        jLabel9.setFont(new java.awt.Font("Felix Titling", 1, 11)); // NOI18N
        jLabel9.setText(" book editor");

        btnDeleteall.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnDeleteall.setText("DELETE ALL");
        btnDeleteall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteallActionPerformed(evt);
            }
        });

        btnLeave.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        btnLeave.setText(" LEAVE");
        btnLeave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeaveActionPerformed(evt);
            }
        });

        jTextData.setColumns(20);
        jTextData.setRows(5);
        jScrollPane2.setViewportView(jTextData);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(364, 364, 364)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(81, 81, 81)
                            .addComponent(btnSave)
                            .addGap(58, 58, 58)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnDeleteall)
                                .addComponent(btnShowData))
                            .addGap(26, 26, 26)
                            .addComponent(btnLeave))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtBookEditor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtYearPublished, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtEdittionBook, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAuthorBook, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cmbBookColor, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cmbBookSize, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNameBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNameBook, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBookSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbBookColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAuthorBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEdittionBook, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtYearPublished, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBookEditor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnShowData)
                    .addComponent(btnLeave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnDeleteall, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameBookActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameBookActionPerformed

    private void btnShowDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowDataActionPerformed

                
    }//GEN-LAST:event_btnShowDataActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         Book Book;
        String NameBook;
        String BookSize;
        String BookColor;
        int EdittionBook;
        String AuthorBook;
        int YearPublished;
        String BookEditor;
        

        BookController BookController = new BookController();

        NameBook = txtNameBook.getText();
        BookSize = cmbBookSize.getSelectedItem().toString();
        BookColor = cmbBookColor.getSelectedItem().toString();
        EdittionBook =  Integer.parseInt(txtEdittionBook.getText());
        AuthorBook = txtAuthorBook.getText();
        YearPublished = Integer.parseInt(txtYearPublished.getText());
        BookEditor = txtBookEditor.getText();
        

        Book =new Book (NameBook,BookSize,BookColor,EdittionBook,AuthorBook, YearPublished,BookEditor);

        BookController.save(Book);

        JOptionPane.showMessageDialog(rootPane,Book.getNameBook());
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteallActionPerformed
        int integer = 0;

        txtNameBook.setText("");
        txtAuthorBook.setText("");
        txtEdittionBook.setText("");
        txtYearPublished.setText("");
        txtBookEditor.setText("");

    }//GEN-LAST:event_btnDeleteallActionPerformed

    private void btnLeaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeaveActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnLeaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteall;
    private javax.swing.JButton btnLeave;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnShowData;
    private javax.swing.JComboBox<String> cmbBookColor;
    private javax.swing.JComboBox<String> cmbBookSize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextData;
    private javax.swing.JTextField txtAuthorBook;
    private javax.swing.JTextField txtBookEditor;
    private javax.swing.JTextField txtEdittionBook;
    private javax.swing.JTextField txtNameBook;
    private javax.swing.JTextField txtYearPublished;
    // End of variables declaration//GEN-END:variables

}
